name: BedWarsSetup
main: me.moonlight.bedwarssetup.Main
version: 1.0.5
author: _MoonLightz
depend: [BedWars1058]

permissions:
  bedwarssetup.setup:
    description: Allow the player to use setup items
    default: op

commands:
  bedwarssetup:
    description: BedWarsSetup main command
    usage: /<command>
    aliases: [bs, bedwarss, bsetup]
    permission: bedwarssetup.setup